export const LOGIN = "LOGIN";
export const BUSINESS_INFO_ARRAY = "BUSINESS_INFO_ARRAY";
export const BUSINESS_EMAIL = "BUSINESS_EMAIL";
export const GET_BUSINESS_APPOINTMENT = "GET_BUSINESS_APPOINTMENT";
export const GET_CUSTOMER_APPOINTMENT = "GET_CUSTOMER_APPOINTMENT";